// The Transport Client (requirement 3, design "Transport Client").
//
// Holds the Socket.IO connection to `/ws`: builds the handshake `auth`, reconnects
// with exponential backoff, sends a fresh project context snapshot on every
// connection, surfaces the connection state to the UI, and decides what to do when
// the server refuses a handshake.
//
// Nothing here includes socket.io-client-cpp, websocketpp, asio, or nlohmann/json.
// The library-facing half is `SocketIoConnection`, declared at the bottom of this
// header and defined in transport_client.cpp — the same arrangement as
// `ReaperTransportActionInvoker` in transport_handler.h, and for the same structural
// reason: the suite globs `tests/**/*.cpp` and compiles the logic under test directly
// into the test binary, so logic that lives in a `src/*.cpp` is logic the suite cannot
// reach. Everything in this file runs in the suite with no network, no TLS stack, and
// no Socket.IO client installed.
//
// ---------------------------------------------------------------------------
// Four properties are made structural rather than checked
//
// These are the four things about this component that a comment could not defend,
// so each one is arranged so that the wrong version does not compile or cannot be
// expressed.
//
// **TLS on every outbound connection (requirement 26.3).** `SecureEndpoint` has a
// private constructor and one producer, `secure_endpoint_for_host`, which writes the
// `https://` scheme itself from a literal. A caller cannot supply a scheme — a host
// that already carries one is refused — so there is no argument that could name
// `http`, and no flag to get wrong at connection time. The second half of the
// enforcement is in transport_client.cpp: the pinned client selects TLS at *compile*
// time through `SIO_TLS` and rewrites the scheme of whatever URL it is handed, so
// that translation unit refuses to compile without it. See the comment there — a
// non-TLS build would silently downgrade `https://` to `ws://`, which is exactly the
// failure a runtime check would miss.
//
// **`clientType` and `protocolVersion` are not settable (requirements 3.1, 20.5).**
// They are `static constexpr` members of `HandshakeAuth`, not fields. There is one
// value of each and no constructor argument that could carry a different one. The
// protocol version comes from `transport/schema_bundle_version.h`, generated by CMake
// from the vendored `MANIFEST.json` at configure time — the value belongs to the build
// that was compiled against those schemas, which a runtime read of the manifest would
// not guarantee. That header explains the choice in full.
//
// **A fresh access token in every handshake (requirement 3.2).** `TransportClient`
// has no member of type `secret_string` and no member holding a `HandshakeAuth`. The
// auth is a local inside `attempt_handshake`, constructed from a fresh
// `AccessTokenSource::current_access_token()` call and destroyed when the call
// returns; `HandshakeAuth` is move-only, so it cannot be copied into a member on the
// way past. There is nowhere for a stale token to be kept.
//
//   This is also why the client owns its own reconnection rather than delegating to
//   the Socket.IO client's. The pinned client replays the URL and query string it was
//   first given when it reconnects internally, so an internally-reconnected socket
//   presents the *original* token — precisely the stale handshake requirement 3.2
//   exists to prevent. transport_client.cpp therefore sets the library's reconnect
//   attempts to zero and every attempt originates here.
//
// **Retry once after a token refresh, and only once (requirement 3.6).** This is a
// state, not a counter — `handshake_attempt` — and the bound follows from the shape of
// the transition rather than from remembering to reset something.
// `decide_after_handshake_rejection` is total over the product of the two attempt
// kinds and every rejection, and `attempt_after` is the only route into
// `single_retry_after_token_refresh`: it is produced by exactly one decision, and that
// decision is unreachable *from* `single_retry_after_token_refresh`. So a token
// rejection on the retry cannot decide to retry again, whatever order events arrive
// in, and there is no counter that a forgotten reset could leave at zero. The suite
// asserts it over the whole product rather than over a scenario.
//
// ---------------------------------------------------------------------------
// The rejection vocabulary is the server's, quoted
//
// The codes below are `CONNECTION_REJECTION_CODES` and `AUTHENTICATION_ERROR_CODES`
// from `server/mcp-server/src/components/socket-io-manager.js` and
// `server/mcp-server/src/middleware/jwt-auth.js`. The server attaches them to the
// handshake refusal as `data.code`, which is what the client reads off the Socket.IO
// error packet. They are quoted here rather than paraphrased, and anything
// unrecognised classifies as `unrecognised` and backs off — the safe direction for a
// server whose protocol is ahead of this build.
//
// Two of them, `missing_client_type` and `invalid_client_type`, are unreachable unless
// this build is broken or the server dropped `extension` from its supported list,
// since `clientType` is a compile-time constant here. They are classified distinctly
// so a log line names which, and they back off like anything else — no acceptance
// criterion covers them, and inventing a terminal state for them is not this task's
// to invent. Recorded so the gap is visible.
//
// ---------------------------------------------------------------------------
// One thread, and which one
//
// This class holds no lock and is not thread-safe. It belongs to the network thread,
// which is where the Socket.IO client's callbacks arrive and where the Envelope Codec
// already runs (requirement 4.5) — so `on_connected`, `on_disconnected`,
// `on_handshake_rejected`, and `reconnect_if_due` are all called from there and the
// state has one owner.
//
// That puts `reconnect_if_due` on the network thread rather than on the REAPER timer
// tick, which is worth being explicit about because the tick is where the rest of this
// extension's periodic work happens. Driving it from the tick would mean the main thread
// and the library's io thread both mutating this object, and the reconnection schedule
// is not worth a mutex on the connection state. The only thing that crosses to the main
// thread is the published status, and it crosses the way everything else does: through
// the queue pair, which is what the production `ConnectionStatePresenter` writes to.
// Requirement 2.3 has the Main Thread Dispatcher as the only component that publishes UI
// state to CEF, and this arrangement is what keeps that true.
//
// ---------------------------------------------------------------------------
// The backoff schedule has no jitter, deliberately
//
// `reconnection_delay_for_attempt` is a pure function of the consecutive failure
// count: 500 ms doubling to a 30 second cap. Deterministic, so the suite can state
// monotonicity and the cap as properties rather than sampling a distribution.
//
// The cost is honest and worth writing down: when the server itself goes down, every
// connected extension reconnects on the same schedule, so the recovery is a series of
// synchronised waves rather than a smooth ramp. The 30 second cap is what bounds it —
// in steady state the fan-in is the connected population divided by thirty seconds,
// which is a load the server is sized for. Jitter would smooth the waves and would
// also make the schedule untestable as a property, and nothing in requirement 3
// asks for it. If it is ever wanted, it belongs as a bounded perturbation *of* this
// schedule so that the property still holds.

#ifndef SESH_AI_TRANSPORT_TRANSPORT_CLIENT_H
#define SESH_AI_TRANSPORT_TRANSPORT_CLIENT_H

#include <auth/secret_string.h>
#include <transport/schema_bundle_version.h>

#include <chrono>
#include <cstddef>
#include <functional>
#include <optional>
#include <string>
#include <string_view>
#include <utility>

// The Socket.IO client's own type, held only as a pointer by SocketIoConnection so
// that this header does not include sio_client.h. Naming the class here is a forward
// declaration of the same type the library defines, the same way transport_handler.h
// forward-declares reaper_plugin_info_t.
namespace sio {
	class client;
}

namespace sesh_ai::transport {

	// -----------------------------------------------------------------------
	// The endpoint, and TLS
	// -----------------------------------------------------------------------

	// Written by secure_endpoint_for_host from this literal and nowhere else. See the
	// header comment on why a caller cannot supply a scheme.
	inline constexpr std::string_view secure_url_scheme{"https://"};

	// The Socket.IO *path* — `SOCKET_IO_PATH` in the server's socket-io-manager.js.
	// Not a namespace: the server passes it as engine.io's `path` option and both
	// clients connect to the default namespace underneath it.
	//
	// The trailing slash is load-bearing and is the kind of thing that costs an
	// afternoon. Engine.io normalises its configured path to end in a slash and
	// matches an incoming request with a prefix test, so a request for `/ws?EIO=4`
	// does not match `/ws/` and is answered with a 404 rather than a handshake. The
	// pinned client builds its URL by concatenating the resource it parsed out of the
	// URL it was given with the query string, so the slash has to be in the URL this
	// side produces.
	inline constexpr std::string_view socket_io_path{"/ws/"};

	// TLS's default port, written into the URL explicitly. The pinned client asks
	// websocketpp's URI parser for the port and interpolates whatever it answers, so
	// stating it removes a dependency on that parser's scheme-to-port table for the
	// one value that must not be wrong.
	inline constexpr unsigned short default_tls_port = 443;

	// A URL that cannot name a plaintext transport.
	//
	// The constructor is private and `secure_endpoint_for_host` is its only friend, so
	// every instance was built by the one function that writes the scheme. There is no
	// mutator, so an endpoint cannot be edited into a plaintext one after the fact.
	class SecureEndpoint final {
	public:
		// `https://host:port/ws/` — what the Socket.IO client is handed.
		const std::string& url() const { return url_; }

		const std::string& host() const { return host_; }

		unsigned short port() const { return port_; }

	private:
		SecureEndpoint(std::string url, std::string host, unsigned short port)
			: url_{std::move(url)},
			host_{std::move(host)},
			port_{port}
		{
		}

		friend std::optional<SecureEndpoint> secure_endpoint_for_host(
			std::string_view host,
			unsigned short port
		);

		std::string url_;
		std::string host_;
		unsigned short port_;
	};

	// Whether a character can appear in a host name this side is willing to build a
	// URL from. Deliberately narrow: letters, digits, `-`, `.`, and `_`. A colon, a
	// slash, an at-sign, a space, or a control character is refused rather than
	// escaped, because every one of them is a way to make the resulting URL mean
	// something other than what the caller wrote.
	//
	// IPv6 literals are refused as a consequence, since they need the colons. The
	// extension connects to a named host behind Nginx, so that is a limitation with no
	// use case rather than a gap.
	inline constexpr bool is_permitted_host_character(char character)
	{
		return (character >= 'a' && character <= 'z')
			|| (character >= 'A' && character <= 'Z')
			|| (character >= '0' && character <= '9')
			|| character == '-'
			|| character == '.'
			|| character == '_';
	}

	// The only way to obtain a SecureEndpoint.
	//
	// Empty for a host this function will not build a URL from: empty, port zero, or
	// carrying any character that is not plainly part of a host name — which refuses a
	// scheme (`https://sesh.example` contains `:` and `/`), a path, a userinfo
	// component, and a port smuggled into the host string. The scheme is this
	// function's to write, and the refusal is what keeps that true.
	inline std::optional<SecureEndpoint> secure_endpoint_for_host(
		std::string_view host,
		unsigned short port = default_tls_port
	)
	{
		if (host.empty() || port == 0) {
			return std::nullopt;
		}

		for (const char character : host) {
			if (!is_permitted_host_character(character)) {
				return std::nullopt;
			}
		}

		// A host that is nothing but separators is not a host.
		if (host.front() == '.' || host.back() == '.' || host.front() == '-') {
			return std::nullopt;
		}

		std::string url;

		url.append(secure_url_scheme);
		url.append(host);
		url.push_back(':');
		url.append(std::to_string(port));
		url.append(socket_io_path);

		return SecureEndpoint{std::move(url), std::string{host}, port};
	}

	// -----------------------------------------------------------------------
	// The handshake `auth`
	// -----------------------------------------------------------------------

	// The three field names the server reads off `socket.handshake.auth`. Quoted from
	// the server's own `readHandshakeAuth` and `resolveClientType`, so the two sides
	// do not carry independent spellings of the same contract.
	//
	// `token` rather than `accessToken`: the server reads `handshakeAuth.token`.
	inline constexpr std::string_view handshake_auth_token_field{"token"};
	inline constexpr std::string_view handshake_auth_client_type_field{"clientType"};
	inline constexpr std::string_view handshake_auth_protocol_version_field{"protocolVersion"};

	// One of the server's two `CLIENT_TYPES`. The extension is always this one, which
	// is why it is a constant rather than a field — see the header comment.
	inline constexpr std::string_view extension_client_type{"extension"};

	// What goes into one handshake, and it goes into exactly one.
	//
	// Move-only, so it cannot be copied into a member on its way to the socket. The
	// token is a `secret_string`, so it has no `operator<<`, no implicit conversion to
	// a string, and no Catch2 stringifier — a failing assertion in this suite prints
	// `{?}` rather than a producer's access token into a public CI log.
	class HandshakeAuth final {
	public:
		explicit HandshakeAuth(auth::secret_string access_token)
			: access_token_{std::move(access_token)}
		{
		}

		HandshakeAuth(const HandshakeAuth&) = delete;
		HandshakeAuth& operator=(const HandshakeAuth&) = delete;
		HandshakeAuth(HandshakeAuth&&) = default;
		HandshakeAuth& operator=(HandshakeAuth&&) = delete;

		const auth::secret_string& access_token() const { return access_token_; }

		// Not fields. There is one value of each in this build and no way to supply
		// another — requirements 3.1 and 20.5 held structurally rather than by a call
		// site remembering to pass the right string.
		static constexpr std::string_view client_type() { return extension_client_type; }

		static constexpr std::string_view protocol_version()
		{
			return schema_bundle::protocol_version;
		}

		// What a log line may say about a handshake. Reports the token's length and
		// never its characters, via `secret_string::describe_for_log`.
		std::string describe_for_log() const
		{
			std::string description{handshake_auth_client_type_field};

			description += '=';
			description.append(client_type());
			description += ' ';
			description.append(handshake_auth_protocol_version_field);
			description += '=';
			description.append(protocol_version());
			description += ' ';
			description.append(handshake_auth_token_field);
			description += '=';
			description += access_token_.describe_for_log();

			return description;
		}

	private:
		auth::secret_string access_token_;
	};

	// -----------------------------------------------------------------------
	// Connection state, as the UI sees it
	// -----------------------------------------------------------------------

	// Requirement 3.4's three values, and only those three. "Connecting" is not one of
	// them: an attempt in flight reports `reconnecting`, which is the honest reading
	// for the producer either way — something is being tried and nothing is connected.
	enum class connection_state {
		connected,
		reconnecting,
		disconnected
	};

	inline constexpr std::string_view describe_connection_state(connection_state state)
	{
		switch (state) {
			case connection_state::connected:
				return "connected";
			case connection_state::reconnecting:
				return "reconnecting";
			case connection_state::disconnected:
				return "disconnected";
		}

		return "unknown";
	}

	// Whether the producer has to do something before the extension can reconnect.
	//
	// Separate from `connection_state` because the two answer different questions and
	// collapsing them would give the UI a state it cannot render: `disconnected` alone
	// does not say whether the extension is about to recover on its own.
	enum class producer_action {
		// Nothing to do. Either connected, or reconnecting on its own.
		none,

		// Requirement 3.5. Another REAPER instance holds the session.
		close_the_other_reaper_instance,

		// Requirement 3.6. The token could not be renewed.
		sign_in_again
	};

	inline constexpr std::string_view describe_producer_action(producer_action action)
	{
		switch (action) {
			case producer_action::none:
				return "none";
			case producer_action::close_the_other_reaper_instance:
				return "close_the_other_reaper_instance";
			case producer_action::sign_in_again:
				return "sign_in_again";
		}

		return "unknown";
	}

	// Producer-facing notices.
	//
	// Held as constants so the suite can assert which one a given path produces, and
	// so the strings are in one place when internationalisation lands (the CEF UI uses
	// react-i18next, so these become keys rather than English — at which point these
	// constants are what the keys are derived from).
	//
	// The duplicate notice names the actual cause. The server refuses a second
	// `extension` connection for the same user, and by far the likeliest reason a
	// producer meets it is having REAPER open twice — so the message says that rather
	// than reporting a code.
	inline constexpr std::string_view connected_notice{
		"Connected to Sesh AI."
	};

	inline constexpr std::string_view reconnecting_notice{
		"Reconnecting to Sesh AI."
	};

	inline constexpr std::string_view session_conflict_notice{
		"Another REAPER instance is already signed in to Sesh AI with this account. "
		"Close the other instance, then reconnect."
	};

	inline constexpr std::string_view sign_in_again_notice{
		"Your Sesh AI sign-in has expired and could not be renewed. Sign in again to reconnect."
	};

	inline constexpr std::string_view signed_out_notice{
		"Sign in to connect to Sesh AI."
	};

	// -----------------------------------------------------------------------
	// Why a handshake was refused
	// -----------------------------------------------------------------------

	// The server's stable rejection codes, quoted. See the header comment.
	inline constexpr std::string_view missing_token_rejection_code{"missing_token"};
	inline constexpr std::string_view invalid_token_rejection_code{"invalid_token"};
	inline constexpr std::string_view expired_token_rejection_code{"expired_token"};
	inline constexpr std::string_view authentication_service_unavailable_rejection_code{
		"authentication_service_unavailable"
	};
	inline constexpr std::string_view missing_client_type_rejection_code{"missing_client_type"};
	inline constexpr std::string_view invalid_client_type_rejection_code{"invalid_client_type"};
	inline constexpr std::string_view duplicate_client_type_rejection_code{"duplicate_client_type"};

	// Requirement 17.6 needs no code of its own, and that is worth stating because the
	// server has one that looks like it should be used here.
	//
	// When the server notices that a connected socket's token has passed `exp`, it
	// pushes an `error:authentication` envelope whose `payload.code` is
	// `expired_token` — one of the codes above — and then drops the socket. Its
	// `TOKEN_EXPIRED_DISCONNECT_REASON` of `token_expired` is an internal registry and
	// log value that never crosses the wire, so nothing on this side should be matching
	// it. The Message Dispatcher hands the envelope's code to `on_disconnected`, which
	// runs it through the same classification as a handshake refusal, and the recovery
	// is the refresh-and-retry-once path requirement 3.6 already describes.

	// The refusal reasons this client distinguishes, which is fewer than the codes
	// above because several of them call for the same response.
	enum class handshake_rejection {
		// `missing_token`, `invalid_token`, `expired_token`. A refreshed token is
		// worth one attempt (requirement 3.6).
		invalid_or_expired_token,

		// `duplicate_client_type`. Terminal (requirement 3.5).
		duplicate_client_type,

		// `missing_client_type`, `invalid_client_type`. Unreachable from a correct
		// build — see the header comment.
		unsupported_client_type,

		// `authentication_service_unavailable`. The server could not reach Cognito's
		// key set. Distinguished from a bad token because refreshing this side's token
		// cannot help and the condition is transient.
		authentication_service_unavailable,

		// No code at all: the connection never got an answer. DNS, TLS, timeout,
		// refused connection.
		network_or_timeout,

		// A code this build does not know. The server's protocol is ahead of this one.
		unrecognised
	};

	inline constexpr std::string_view describe_handshake_rejection(handshake_rejection rejection)
	{
		switch (rejection) {
			case handshake_rejection::invalid_or_expired_token:
				return "invalid_or_expired_token";
			case handshake_rejection::duplicate_client_type:
				return "duplicate_client_type";
			case handshake_rejection::unsupported_client_type:
				return "unsupported_client_type";
			case handshake_rejection::authentication_service_unavailable:
				return "authentication_service_unavailable";
			case handshake_rejection::network_or_timeout:
				return "network_or_timeout";
			case handshake_rejection::unrecognised:
				return "unrecognised";
		}

		return "unknown";
	}

	// The server's code, classified. An empty code means the refusal carried none,
	// which is what a connection that never reached the server looks like.
	//
	// Exact comparison rather than substring matching: these are stable machine codes
	// on both sides, and a substring test would classify a future
	// `duplicate_client_type_pending` as the terminal case on the strength of a prefix.
	inline handshake_rejection classify_handshake_rejection(std::string_view server_rejection_code)
	{
		if (server_rejection_code.empty()) {
			return handshake_rejection::network_or_timeout;
		}

		if (server_rejection_code == duplicate_client_type_rejection_code) {
			return handshake_rejection::duplicate_client_type;
		}

		if (server_rejection_code == missing_token_rejection_code
			|| server_rejection_code == invalid_token_rejection_code
			|| server_rejection_code == expired_token_rejection_code) {
			return handshake_rejection::invalid_or_expired_token;
		}

		if (server_rejection_code == missing_client_type_rejection_code
			|| server_rejection_code == invalid_client_type_rejection_code) {
			return handshake_rejection::unsupported_client_type;
		}

		if (server_rejection_code == authentication_service_unavailable_rejection_code) {
			return handshake_rejection::authentication_service_unavailable;
		}

		return handshake_rejection::unrecognised;
	}

	// -----------------------------------------------------------------------
	// The retry-once bound, as a state
	// -----------------------------------------------------------------------

	// Which kind of attempt the next handshake is. See the header comment — this is
	// what makes requirement 3.6's "retry once" structural instead of a counter.
	enum class handshake_attempt {
		// An ordinary attempt: the first one, or one scheduled by the backoff.
		first_or_backoff,

		// The single attempt permitted after a token refresh. Reachable only from
		// `first_or_backoff`, and never from itself.
		single_retry_after_token_refresh
	};

	inline constexpr std::string_view describe_handshake_attempt(handshake_attempt attempt)
	{
		switch (attempt) {
			case handshake_attempt::first_or_backoff:
				return "first_or_backoff";
			case handshake_attempt::single_retry_after_token_refresh:
				return "single_retry_after_token_refresh";
		}

		return "unknown";
	}

	// What to do about a refused handshake.
	enum class reconnection_decision {
		// Requirement 3.6, first clause. Ask the Token Manager for a fresh token and
		// try again immediately — the token was the problem and a delay would not fix
		// it.
		refresh_token_and_retry_once,

		// Requirement 3.6, second clause. The retry was refused on the token too.
		prompt_sign_in,

		// Requirements 3.2 and 3.6's third clause.
		back_off_and_reconnect,

		// Requirement 3.5. No automatic retry, ever.
		stop_and_report_session_conflict
	};

	inline constexpr std::string_view describe_reconnection_decision(reconnection_decision decision)
	{
		switch (decision) {
			case reconnection_decision::refresh_token_and_retry_once:
				return "refresh_token_and_retry_once";
			case reconnection_decision::prompt_sign_in:
				return "prompt_sign_in";
			case reconnection_decision::back_off_and_reconnect:
				return "back_off_and_reconnect";
			case reconnection_decision::stop_and_report_session_conflict:
				return "stop_and_report_session_conflict";
		}

		return "unknown";
	}

	// Requirement 3.6's decision table, total over both attempt kinds and every
	// rejection.
	//
	// The duplicate case is first and does not consult the attempt kind at all, which
	// is what makes requirement 3.5 unconditional: there is no attempt kind, no
	// ordering of events, and no refresh outcome that produces a retry for it.
	constexpr reconnection_decision decide_after_handshake_rejection(
		handshake_attempt attempt,
		handshake_rejection rejection
	)
	{
		if (rejection == handshake_rejection::duplicate_client_type) {
			return reconnection_decision::stop_and_report_session_conflict;
		}

		// Everything that is not an authentication rejection is a transient condition
		// that a token cannot fix — an unreachable server, a Cognito key set the
		// server could not fetch, a code this build does not know. All of them back
		// off, which is the safe direction for the one that is a protocol mismatch.
		if (rejection != handshake_rejection::invalid_or_expired_token) {
			return reconnection_decision::back_off_and_reconnect;
		}

		switch (attempt) {
			case handshake_attempt::first_or_backoff:
				return reconnection_decision::refresh_token_and_retry_once;
			case handshake_attempt::single_retry_after_token_refresh:
				return reconnection_decision::prompt_sign_in;
		}

		return reconnection_decision::back_off_and_reconnect;
	}

	// The attempt kind a decision leaves behind.
	//
	// One decision yields the retry state and every other yields the ordinary one, so
	// the retry entitlement is granted by a single transition and spent by taking it.
	constexpr handshake_attempt attempt_after(reconnection_decision decision)
	{
		return decision == reconnection_decision::refresh_token_and_retry_once
			? handshake_attempt::single_retry_after_token_refresh
			: handshake_attempt::first_or_backoff;
	}

	// -----------------------------------------------------------------------
	// The backoff schedule
	// -----------------------------------------------------------------------

	inline constexpr std::chrono::milliseconds initial_reconnection_delay{500};
	inline constexpr std::chrono::milliseconds maximum_reconnection_delay{30 * 1000};

	// Requirement 3.2. 500 ms doubling per consecutive failure, capped at 30 seconds.
	//
	// Zero for zero failures, which is what makes the first attempt immediate without
	// needing a special case at the call site.
	//
	// Doubling in a loop with the cap tested inside it rather than shifting by the
	// attempt count: a shift overflows for a large count and a cap applied afterwards
	// would then compare against a wrapped value, so a client that had been failing
	// for a week could produce a *shorter* delay than one that had been failing for a
	// second. The loop cannot: it returns the cap the moment it reaches it, so it runs
	// a handful of iterations whatever the count.
	constexpr std::chrono::milliseconds reconnection_delay_for_attempt(
		std::size_t consecutive_failed_attempts
	)
	{
		if (consecutive_failed_attempts == 0) {
			return std::chrono::milliseconds::zero();
		}

		std::chrono::milliseconds delay = initial_reconnection_delay;

		for (std::size_t doubling = 1; doubling < consecutive_failed_attempts; ++doubling) {
			if (delay >= maximum_reconnection_delay) {
				return maximum_reconnection_delay;
			}

			delay *= 2;
		}

		return delay > maximum_reconnection_delay ? maximum_reconnection_delay : delay;
	}

	// -----------------------------------------------------------------------
	// What the UI is given
	// -----------------------------------------------------------------------

	// Published on every state change. Carries no token material, and the suite
	// asserts that.
	struct connection_status {
		connection_state state = connection_state::disconnected;

		// Reset to zero by a successful connection, so a drop after a long healthy
		// session starts the schedule at the beginning rather than wherever the last
		// outage left it.
		std::size_t consecutive_failed_attempts = 0;

		// The delay currently being waited out. Zero when nothing is scheduled.
		std::chrono::milliseconds reconnection_delay{0};

		producer_action required_producer_action = producer_action::none;

		// Producer-facing. One of the notices above.
		std::string notice;

		// Why the last handshake was refused, for the log and for diagnosis. Empty
		// when no handshake has been refused since the last successful connection.
		std::optional<handshake_rejection> last_rejection;
	};

	// -----------------------------------------------------------------------
	// The four seams
	// -----------------------------------------------------------------------

	// The Socket.IO client. One operation each way, which is this component's whole
	// dependency on the library.
	//
	// `open` takes the auth by const reference and the implementation serialises it
	// into the handshake without keeping it, which is the other half of "a fresh token
	// in every handshake" — there is no overload that accepts a stored auth.
	class SocketConnection {
	public:
		virtual ~SocketConnection() = default;

		// False when the attempt could not be started at all: no client, a URL the
		// library refused, no route. Not a report that the handshake succeeded — that
		// arrives later, through `TransportClient::on_connected`.
		virtual bool open(const SecureEndpoint& endpoint, const HandshakeAuth& handshake_auth) = 0;

		// Idempotent by contract: the client closes a connection that may already be
		// closed, and must not receive a disconnect callback it has to reason about as
		// a new event.
		virtual void close() = 0;
	};

	// What a token refresh did. The same three fields as
	// `auth::operation_outcome`, restated here so that this header does not include
	// the whole Token Manager — `transport/token_manager_access_token_source.h` is
	// where the two meet.
	//
	// `retryable` is the load-bearing field. A refused refresh token is terminal and
	// the producer has to sign in; an unreachable token endpoint is not, and the next
	// tick tries again. Treating them the same would either prompt a sign-in for a
	// dropped Wi-Fi connection or loop forever on a revoked session.
	struct token_refresh_outcome {
		bool succeeded = false;
		bool retryable = false;
		std::string failure_reason;
	};

	// The Token Manager, narrowed to the two operations this component needs
	// (requirements 3.1, 3.6, 17.6).
	class AccessTokenSource {
	public:
		virtual ~AccessTokenSource() = default;

		// Empty when there is no token worth putting in a handshake — not signed in,
		// or signed in with a token that has already expired. The client treats that
		// as a sign-in prompt rather than as a network failure, because a handshake
		// with no token is one the server refuses by design.
		virtual std::optional<auth::secret_string> current_access_token() = 0;

		virtual token_refresh_outcome refresh_access_token() = 0;
	};

	// Requirement 3.3. Whatever builds and sends the project context snapshot.
	//
	// Narrow to one operation on purpose: this component's concern is *when* a
	// snapshot is sent, not what is in it. The Context Builder owns the content.
	class ProjectContextSnapshotPublisher {
	public:
		virtual ~ProjectContextSnapshotPublisher() = default;

		// False when the snapshot could not be produced or queued. Reported so a
		// failure appears in the log line rather than as a server that never received
		// one; requirement 3.3 specifies the send, not a retry, so the client records
		// the outcome and does not schedule another.
		virtual bool publish_project_context_snapshot() = 0;
	};

	// Requirement 3.4. Where the connection state goes.
	//
	// In production this is the Main Thread Dispatcher, which is the only component
	// permitted to publish UI state to CEF (requirement 2.3) — so the implementation
	// of this seam hands the status to the outbound side of the queue pair rather than
	// touching CEF from the network thread.
	class ConnectionStatePresenter {
	public:
		virtual ~ConnectionStatePresenter() = default;

		virtual void present_connection_status(const connection_status& status) = 0;
	};

	// -----------------------------------------------------------------------
	// The client
	// -----------------------------------------------------------------------

	// Monotonic, for the same reason the Token Manager's clock is: a reconnection that
	// is due must not become un-due because the producer changed the system clock or
	// NTP stepped it.
	using steady_clock = std::chrono::steady_clock;
	using clock_reader = std::function<steady_clock::time_point()>;

	class TransportClient {
	public:
		TransportClient(
			SecureEndpoint endpoint,
			SocketConnection& socket_connection,
			AccessTokenSource& access_token_source,
			ProjectContextSnapshotPublisher& snapshot_publisher,
			ConnectionStatePresenter& state_presenter,
			clock_reader read_clock = {})
			: endpoint_{std::move(endpoint)},
			socket_connection_{socket_connection},
			access_token_source_{access_token_source},
			snapshot_publisher_{snapshot_publisher},
			state_presenter_{state_presenter},
			read_clock_{read_clock ? std::move(read_clock) : clock_reader{[] { return steady_clock::now(); }}}
		{
			status_.notice.assign(signed_out_notice);
		}

		// One connection, in one place. The socket's callbacks hold this object's
		// address.
		TransportClient(const TransportClient&) = delete;
		TransportClient& operator=(const TransportClient&) = delete;
		TransportClient(TransportClient&&) = delete;
		TransportClient& operator=(TransportClient&&) = delete;

		const SecureEndpoint& endpoint() const { return endpoint_; }

		const connection_status& status() const { return status_; }

		connection_state state() const { return status_.state; }

		// Requirement 3.1. The first attempt. Refuses while the client is holding for
		// a producer action, which is what makes requirement 3.5 hold against a caller
		// that keeps calling connect() — see `attempt_handshake`.
		bool connect()
		{
			return attempt_handshake();
		}

		// Reported by the adapter when the server accepted the handshake.
		void on_connected()
		{
			if (has_shut_down_) {
				return;
			}

			mark_connected();
		}

		// Reported by the adapter when an open socket closed, and by the Message
		// Dispatcher when the server pushed an `error:authentication` envelope ahead of
		// dropping the socket — that envelope's `payload.code` is the code to pass.
		//
		// An empty code is a plain drop: the socket went away and the server said
		// nothing, which classifies as a network failure and backs off (requirements
		// 3.2, 23.1). A code of `expired_token` is requirement 17.6's case, and it
		// recovers through the refresh-and-retry-once path rather than through one of
		// its own.
		void on_disconnected(std::string_view server_rejection_code = {})
		{
			if (is_quiescent()) {
				return;
			}

			apply_connection_failure(classify_handshake_rejection(server_rejection_code));
		}

		// Reported by the adapter when the server refused the handshake. The code is
		// `data.code` off the Socket.IO error packet.
		//
		// Deliberately the same decision as `on_disconnected`. The two are separate
		// entry points because a log line and a call site should say which event
		// happened, but a socket dropped for an expired token and a handshake refused
		// for an expired token need the same response, and one table is why requirement
		// 17.6 needs no path of its own.
		void on_handshake_rejected(std::string_view server_rejection_code)
		{
			if (is_quiescent()) {
				return;
			}

			apply_connection_failure(classify_handshake_rejection(server_rejection_code));
		}

		// What the main-thread tick calls. True when a handshake was started.
		bool reconnect_if_due()
		{
			if (is_quiescent() || !reconnect_due_at_.has_value()) {
				return false;
			}

			if (read_clock_() < *reconnect_due_at_) {
				return false;
			}

			reconnect_due_at_.reset();

			return attempt_handshake();
		}

		// How long until the scheduled reconnection. Empty when none is scheduled,
		// which includes both "connected" and "waiting for the producer".
		std::optional<std::chrono::milliseconds> time_until_reconnection() const
		{
			if (!reconnect_due_at_.has_value()) {
				return std::nullopt;
			}

			const steady_clock::time_point now = read_clock_();

			if (now >= *reconnect_due_at_) {
				return std::chrono::milliseconds::zero();
			}

			return std::chrono::duration_cast<std::chrono::milliseconds>(*reconnect_due_at_ - now);
		}

		// The only way out of a hold, and it is named for who performs it.
		//
		// Requirement 3.5 says the extension must not retry a duplicate rejection
		// automatically, not that a producer who has closed the other REAPER instance
		// is stuck until they restart. Every automatic path — `reconnect_if_due`,
		// `on_disconnected`, `on_handshake_rejected`, and `connect` — refuses while a
		// hold is in place, so this is the single deliberate escape and a test can
		// state that no other route clears it.
		bool reconnect_at_producer_request()
		{
			if (has_shut_down_) {
				return false;
			}

			is_holding_for_session_conflict_ = false;
			is_holding_for_sign_in_ = false;
			next_handshake_attempt_ = handshake_attempt::first_or_backoff;
			status_.consecutive_failed_attempts = 0;
			status_.reconnection_delay = std::chrono::milliseconds::zero();
			status_.last_rejection.reset();
			reconnect_due_at_.reset();

			return attempt_handshake();
		}

		// Terminal. Closes the socket and stops every automatic path for good, which
		// is what REAPER unloading the extension needs.
		void shut_down()
		{
			if (has_shut_down_) {
				return;
			}

			has_shut_down_ = true;
			reconnect_due_at_.reset();
			socket_connection_.close();

			status_.state = connection_state::disconnected;
			status_.required_producer_action = producer_action::none;
			status_.reconnection_delay = std::chrono::milliseconds::zero();
			status_.notice.assign(signed_out_notice);

			publish_status();
		}

		// -------------------------------------------------------------------
		// Observable counters
		//
		// Exposed because they are what the properties in this component are about:
		// "a fresh token per handshake" and "a snapshot per connection" are statements
		// relating two counts, and asserting them beats asserting a scenario.
		// -------------------------------------------------------------------

		// Handshakes started, including the first. One per `SocketConnection::open`
		// call, and each one built its own auth.
		std::size_t handshake_count() const { return handshake_count_; }

		// Successful connections, including the first.
		std::size_t connection_count() const { return connection_count_; }

		// Snapshots requested. Equal to `connection_count()` at every point in this
		// client's life — requirement 3.3.
		std::size_t project_context_snapshot_request_count() const
		{
			return project_context_snapshot_request_count_;
		}

		// Whether the last snapshot request was accepted by the publisher.
		bool last_project_context_snapshot_published() const
		{
			return last_project_context_snapshot_published_;
		}

		bool is_holding_for_session_conflict() const { return is_holding_for_session_conflict_; }

		bool is_holding_for_sign_in() const { return is_holding_for_sign_in_; }

		bool has_shut_down() const { return has_shut_down_; }

		handshake_attempt next_handshake_attempt() const { return next_handshake_attempt_; }

		// For a log line. Never contains token material: the only token-shaped thing
		// this class holds is the one inside `attempt_handshake`, which is gone by the
		// time anything can ask.
		std::string describe_for_log() const
		{
			std::string description{"transport state="};

			description.append(describe_connection_state(status_.state));
			description += " attempts=" + std::to_string(status_.consecutive_failed_attempts);
			description += " delay=" + std::to_string(status_.reconnection_delay.count()) + "ms";
			description += " next_attempt=";
			description.append(describe_handshake_attempt(next_handshake_attempt_));
			description += " producer_action=";
			description.append(describe_producer_action(status_.required_producer_action));
			description += " rejection=";
			description.append(
				status_.last_rejection.has_value()
					? describe_handshake_rejection(*status_.last_rejection)
					: std::string_view{"none"}
			);
			description += " handshakes=" + std::to_string(handshake_count_);
			description += " connections=" + std::to_string(connection_count_);
			description += " snapshots=" + std::to_string(project_context_snapshot_request_count_);
			description += " endpoint=" + endpoint_.url();

			return description;
		}

	private:
		// Whether every automatic path should decline. One predicate rather than three
		// conditions repeated at four call sites, because missing one of them is how
		// requirement 3.5 would quietly stop holding — the socket's own close
		// callback arriving after a duplicate rejection is the specific way that
		// happens.
		bool is_quiescent() const
		{
			return has_shut_down_ || is_holding_for_session_conflict_ || is_holding_for_sign_in_;
		}

		// Builds a fresh handshake `auth` and starts one attempt.
		//
		// The auth is a local. Nothing in this class holds a token, before or after —
		// see the header comment.
		bool attempt_handshake()
		{
			if (is_quiescent()) {
				return false;
			}

			std::optional<auth::secret_string> access_token =
				access_token_source_.current_access_token();

			if (!access_token.has_value() || access_token->empty()) {
				// Not a network failure. A handshake with no token is one the server
				// refuses by design, so backing off would spend the producer's
				// session retrying something that cannot succeed.
				hold_for_sign_in();

				return false;
			}

			++handshake_count_;

			const HandshakeAuth handshake_auth{std::move(*access_token)};

			if (!socket_connection_.open(endpoint_, handshake_auth)) {
				record_failed_attempt_and_schedule_reconnection();

				return false;
			}

			// In flight. Nothing is connected yet, and the producer should see that
			// something is being tried.
			status_.state = connection_state::reconnecting;
			status_.required_producer_action = producer_action::none;
			status_.notice.assign(reconnecting_notice);

			publish_status();

			return true;
		}

		// Requirement 3.3, and the reason it is one function.
		//
		// Recording the connection and requesting the snapshot happen here and only
		// here, so "connected without a snapshot" is not a state this class can be in.
		// A separate `on_connected` that happened to call a publisher would be one
		// early return away from being wrong.
		void mark_connected()
		{
			++connection_count_;

			status_.state = connection_state::connected;
			status_.consecutive_failed_attempts = 0;
			status_.reconnection_delay = std::chrono::milliseconds::zero();
			status_.required_producer_action = producer_action::none;
			status_.notice.assign(connected_notice);
			status_.last_rejection.reset();

			reconnect_due_at_.reset();
			next_handshake_attempt_ = handshake_attempt::first_or_backoff;

			++project_context_snapshot_request_count_;
			last_project_context_snapshot_published_ =
				snapshot_publisher_.publish_project_context_snapshot();

			publish_status();
		}

		// Requirement 3.6, applied. The attempt kind is read once and replaced
		// immediately, so this attempt's retry entitlement is spent whatever happens
		// next.
		void apply_connection_failure(handshake_rejection rejection)
		{
			status_.last_rejection = rejection;

			const handshake_attempt attempt = next_handshake_attempt_;
			const reconnection_decision decision =
				decide_after_handshake_rejection(attempt, rejection);

			next_handshake_attempt_ = attempt_after(decision);

			switch (decision) {
				case reconnection_decision::stop_and_report_session_conflict:
					hold_for_session_conflict();

					return;

				case reconnection_decision::prompt_sign_in:
					hold_for_sign_in();

					return;

				case reconnection_decision::refresh_token_and_retry_once:
					refresh_token_and_retry();

					return;

				case reconnection_decision::back_off_and_reconnect:
					record_failed_attempt_and_schedule_reconnection();

					return;
			}
		}

		// The refresh half of requirement 3.6.
		//
		// On success the retry is immediate rather than delayed: the token was the
		// problem and it has been replaced, so waiting would only extend an outage the
		// producer can see. `next_handshake_attempt_` is already the retry state by
		// the time this runs, so a second token rejection reaches `prompt_sign_in`.
		void refresh_token_and_retry()
		{
			const token_refresh_outcome refreshed = access_token_source_.refresh_access_token();

			if (refreshed.succeeded) {
				attempt_handshake();

				return;
			}

			// The refresh itself failed, so the retry never happens and its
			// entitlement goes back. Which of the two outcomes follows is the whole
			// reason `retryable` exists: a token endpoint that could not be reached
			// gets another attempt on the next tick, and a refresh token the server
			// refused does not get better by being asked again.
			next_handshake_attempt_ = handshake_attempt::first_or_backoff;

			if (refreshed.retryable) {
				record_failed_attempt_and_schedule_reconnection();

				return;
			}

			hold_for_sign_in();
		}

		// Requirement 3.2. One more failure on the count, a longer delay, and a
		// reconnecting state in the UI.
		void record_failed_attempt_and_schedule_reconnection()
		{
			++status_.consecutive_failed_attempts;
			status_.reconnection_delay =
				reconnection_delay_for_attempt(status_.consecutive_failed_attempts);
			status_.state = connection_state::reconnecting;
			status_.required_producer_action = producer_action::none;
			status_.notice.assign(reconnecting_notice);

			reconnect_due_at_ = read_clock_() + status_.reconnection_delay;

			publish_status();
		}

		// Requirement 3.5. Terminal for every automatic path.
		void hold_for_session_conflict()
		{
			is_holding_for_session_conflict_ = true;

			enter_hold(
				producer_action::close_the_other_reaper_instance,
				session_conflict_notice
			);
		}

		// Requirement 3.6, second clause.
		void hold_for_sign_in()
		{
			is_holding_for_sign_in_ = true;

			enter_hold(producer_action::sign_in_again, sign_in_again_notice);
		}

		// The socket is closed before the flags are read anywhere else, so the
		// disconnect callback that close may produce arrives with `is_quiescent()`
		// already true and is ignored rather than scheduling a reconnection.
		void enter_hold(producer_action action, std::string_view notice)
		{
			reconnect_due_at_.reset();
			socket_connection_.close();

			status_.state = connection_state::disconnected;
			status_.reconnection_delay = std::chrono::milliseconds::zero();
			status_.required_producer_action = action;
			status_.notice.assign(notice);

			publish_status();
		}

		// Requirement 3.4. Every state change goes out; there is no path that changes
		// the status without publishing it.
		void publish_status()
		{
			state_presenter_.present_connection_status(status_);
		}

		SecureEndpoint endpoint_;
		SocketConnection& socket_connection_;
		AccessTokenSource& access_token_source_;
		ProjectContextSnapshotPublisher& snapshot_publisher_;
		ConnectionStatePresenter& state_presenter_;
		clock_reader read_clock_;

		connection_status status_;

		// Deliberately absent: any member holding an access token or a HandshakeAuth.
		// See the header comment — this absence is requirement 3.2's enforcement, and
		// it is the kind of thing that gets helpfully added back as a cache.

		handshake_attempt next_handshake_attempt_ = handshake_attempt::first_or_backoff;
		std::optional<steady_clock::time_point> reconnect_due_at_;

		bool is_holding_for_session_conflict_ = false;
		bool is_holding_for_sign_in_ = false;
		bool has_shut_down_ = false;
		bool last_project_context_snapshot_published_ = false;

		std::size_t handshake_count_ = 0;
		std::size_t connection_count_ = 0;
		std::size_t project_context_snapshot_request_count_ = 0;
	};

	// -----------------------------------------------------------------------
	// The library-facing half
	// -----------------------------------------------------------------------

	// socket.io-client-cpp behind `SocketConnection`. Defined in
	// transport_client.cpp, which is the one translation unit here that includes the
	// library — and which does not compile on a machine that has not populated it.
	//
	// The client is held through a pointer to a forward-declared type, so this header
	// stays free of sio_client.h. That makes the destructor out-of-line by necessity,
	// which is the usual shape and the same one ReaperTransportActionInvoker uses for
	// the REAPER SDK.
	//
	// The callbacks it installs report into the TransportClient it is given, which is
	// why the reference is a constructor argument rather than a setter: a connection
	// with no reporting target is not constructible.
	class SocketIoConnection final : public SocketConnection {
	public:
		SocketIoConnection();
		~SocketIoConnection() override;

		SocketIoConnection(const SocketIoConnection&) = delete;
		SocketIoConnection& operator=(const SocketIoConnection&) = delete;
		SocketIoConnection(SocketIoConnection&&) = delete;
		SocketIoConnection& operator=(SocketIoConnection&&) = delete;

		// Installs the listeners that report into `client`. Called once, before the
		// first `open`. Separate from the constructor because the client holds this
		// connection and the connection reports to the client, and one of the two has
		// to be constructed first.
		void report_to(TransportClient& client);

		bool open(const SecureEndpoint& endpoint, const HandshakeAuth& handshake_auth) override;

		void close() override;

	private:
		sio::client* client_ = nullptr;
		TransportClient* transport_client_ = nullptr;

		// The rejection code from the last Socket.IO error packet, which arrives on a
		// different listener from the failure notification. See transport_client.cpp.
		std::string last_server_rejection_code_;
	};

}

#endif
