# Reader for the vendored schema bundle's MANIFEST.json.
#
# There are two callers, and they run at different times. The top-level
# CMakeLists.txt reads the manifest at configure time to learn the
# protocolVersion and which files the build depends on; VerifySchemaBundle.cmake
# reads it again at build time to check the digests. Both go through this
# function so there is exactly one understanding of the manifest's shape, and a
# format change cannot leave the two halves disagreeing.
#
# Nothing here touches the network. The manifest and the files it describes are
# committed to this repository — see the "Protocol Schemas" section of the
# monorepo's reaper-extension workflow steering, and ADR 0019 for why the bundle
# is a copy rather than a symlink or a runtime fetch.

include_guard(GLOBAL)

# Reads the manifest at manifest_path and returns, in the caller's scope:
#
#   out_protocol_version   the protocolVersion string, derived by the monorepo's
#                          bundler from the digests below
#   out_relative_paths     each file's path, relative to the bundle directory
#   out_digests            the expected SHA-256 for each path, same order
function(sesh_ai_read_schema_manifest
	manifest_path
	out_protocol_version
	out_relative_paths
	out_digests
)
	if(NOT EXISTS "${manifest_path}")
		message(FATAL_ERROR
			"Sesh AI extension: the vendored schema bundle manifest is missing — ${manifest_path}. The "
			"bundle is generated by `npm run schemas:bundle` in the sesh-ai monorepo and committed to "
			"this repository; it is never downloaded. Restore it from the monorepo rather than "
			"reconstructing it here."
		)
	endif()

	file(READ "${manifest_path}" manifest_contents)

	string(JSON protocol_version
		ERROR_VARIABLE protocol_version_error
		GET "${manifest_contents}" "protocolVersion"
	)

	if(protocol_version_error OR protocol_version STREQUAL "")
		message(FATAL_ERROR
			"Sesh AI extension: ${manifest_path} carries no protocolVersion. The Transport Client sends "
			"it in the handshake, so the build cannot proceed without it — ${protocol_version_error}"
		)
	endif()

	string(JSON manifest_file_count
		ERROR_VARIABLE manifest_file_count_error
		LENGTH "${manifest_contents}" "files"
	)

	if(manifest_file_count_error)
		message(FATAL_ERROR
			"Sesh AI extension: ${manifest_path} has no readable `files` array — "
			"${manifest_file_count_error}"
		)
	endif()

	# An empty list would make verification pass by having nothing to check, which
	# is the one outcome worse than failing.
	if(manifest_file_count EQUAL 0)
		message(FATAL_ERROR
			"Sesh AI extension: ${manifest_path} lists no files. Digest verification would pass "
			"vacuously, so this is treated as a corrupt manifest."
		)
	endif()

	set(relative_paths "")
	set(digests "")

	math(EXPR last_entry_index "${manifest_file_count} - 1")

	foreach(entry_index RANGE ${last_entry_index})
		string(JSON manifest_entry GET "${manifest_contents}" "files" ${entry_index})
		string(JSON relative_path GET "${manifest_entry}" "path")
		string(JSON expected_digest GET "${manifest_entry}" "sha256")

		list(APPEND relative_paths "${relative_path}")
		list(APPEND digests "${expected_digest}")
	endforeach()

	set(${out_protocol_version} "${protocol_version}" PARENT_SCOPE)
	set(${out_relative_paths} "${relative_paths}" PARENT_SCOPE)
	set(${out_digests} "${digests}" PARENT_SCOPE)
endfunction()
