# Integrity check for the vendored schema bundle, run as a build step.
#
# Invoked through `cmake -P` by the custom command the top-level CMakeLists.txt
# attaches to the default build target:
#
#   cmake -DSESH_AI_SCHEMA_DIRECTORY=<dir> -P cmake/VerifySchemaBundle.cmake
#
# Two properties are requirements rather than conveniences.
#
# A mismatch fails the build and is never a runtime condition (requirements 20.2,
# 20.3, and 4.6). The C++ was compiled against a fixed set of schema shapes, so a
# file that no longer matches its digest is a broken build, not something to
# discover in a producer's session and try to recover from.
#
# It needs no network. The monorepo checks that this bundle is *fresh*, because
# only it can see both the source and the copy; this repository checks that the
# committed files are *intact*, which it can do offline. That is what keeps the
# macOS, Windows, and Linux build legs reproducible.

cmake_minimum_required(VERSION 3.21)

include("${CMAKE_CURRENT_LIST_DIR}/SchemaBundle.cmake")

if(NOT SESH_AI_SCHEMA_DIRECTORY)
	message(FATAL_ERROR
		"Sesh AI extension: VerifySchemaBundle.cmake needs -DSESH_AI_SCHEMA_DIRECTORY=<path to the "
		"vendored bundle>."
	)
endif()

sesh_ai_read_schema_manifest("${SESH_AI_SCHEMA_DIRECTORY}/MANIFEST.json"
	schema_protocol_version
	schema_relative_paths
	schema_expected_digests
)

list(LENGTH schema_relative_paths schema_file_count)
math(EXPR last_entry_index "${schema_file_count} - 1")

# Every failure is collected before reporting, so one run names every file that
# is wrong. Stopping at the first would turn a stale bundle into a sequence of
# builds that each reveal one more problem.
set(verification_failures "")

foreach(entry_index RANGE ${last_entry_index})
	list(GET schema_relative_paths ${entry_index} relative_path)
	list(GET schema_expected_digests ${entry_index} expected_digest)

	set(absolute_path "${SESH_AI_SCHEMA_DIRECTORY}/${relative_path}")

	if(NOT EXISTS "${absolute_path}")
		list(APPEND verification_failures "missing — ${relative_path}")
		continue()
	endif()

	file(SHA256 "${absolute_path}" actual_digest)

	if(NOT actual_digest STREQUAL expected_digest)
		list(APPEND verification_failures
			"digest mismatch — ${relative_path}: manifest says ${expected_digest}, file hashes to ${actual_digest}"
		)
	endif()
endforeach()

# The digest loop catches an edited or truncated file but cannot notice an added
# one, and a schema the manifest does not list is a file the monorepo's bundler
# did not produce. The validator would happily resolve a $ref into it, so it
# counts as a failure here.
file(GLOB_RECURSE present_schema_files
	RELATIVE "${SESH_AI_SCHEMA_DIRECTORY}"
	"${SESH_AI_SCHEMA_DIRECTORY}/*.json"
)

foreach(present_schema_file IN LISTS present_schema_files)
	if(present_schema_file STREQUAL "MANIFEST.json")
		continue()
	endif()

	if(NOT present_schema_file IN_LIST schema_relative_paths)
		list(APPEND verification_failures "not listed in MANIFEST.json — ${present_schema_file}")
	endif()
endforeach()

if(verification_failures)
	list(JOIN verification_failures "\n    " verification_failure_report)

	message(FATAL_ERROR
		"Sesh AI extension: the vendored schema bundle does not match MANIFEST.json.\n"
		"    ${verification_failure_report}\n"
		"These files are generated by `npm run schemas:bundle` in the sesh-ai monorepo and must never be "
		"edited here. Restore them from the bundler — do not adjust the digests to match, which would "
		"leave the C++ validating against a contract no server speaks."
	)
endif()

message(STATUS
	"Sesh AI extension: vendored schema bundle verified — ${schema_file_count} files, "
	"protocolVersion ${schema_protocol_version}"
)
